/* Vistas de gestión. Los datos privados llegan mediante la clave de Caja. */
(() => {
  "use strict";
  const B=window.KebbaBook;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const money=(n,c="UYU")=>`${c} ${(Number(n||0)/100).toLocaleString("es-UY",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const labelDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d))?d.split("-").reverse().join("/"):d;
  const option=(v,label,selected)=>`<option value="${esc(v)}" ${v===selected?"selected":""}>${esc(label)}</option>`;
  const select=(name,label,options,value)=>`<label class="cash-field">${label}<select name="${name}">${Object.entries(options).map(([v,l])=>option(v,l,value)).join("")}</select></label>`;
  const input=(name,label,value="",type="text",extra="",required=true)=>`<label class="cash-field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?"required":""} ${extra}></label>`;
  const stat=(label,value,detail="")=>`<div class="cash-stat"><span>${label}</span><strong>${value}</strong>${detail?`<small>${detail}</small>`:""}</div>`;
  const amountLabel=e=>e.amount_minor===null?"Sin valorar":money(e.amount_minor,e.currency);
  function toolbar(snapshot,filters,full){
    const names=[...new Set(B.journal(snapshot).flatMap(e=>[e.person,e.recipient]).filter(Boolean))].sort();
    return `<details class="book-filter-panel" ${Object.values(filters).some(Boolean)?"open":""}><summary>${full?"Buscar y filtrar":"Elegir período"} · ${filters.from||filters.to?`${esc(labelDate(filters.from)||"Inicio")} a ${esc(labelDate(filters.to)||"hoy")}`:"Todo el historial"}</summary><form id="cash-book-filter" class="book-filters"><div class="book-filter-grid">${input("from","Desde",filters.from,"date","",false)}${input("to","Hasta",filters.to,"date","",false)}${full?`${input("query","Buscar concepto, proveedor o nota",filters.query,"search","",false)}${select("person","Persona",{"":"Todas",...Object.fromEntries(names.map(n=>[n,n]))},filters.person)}${select("kind","Tipo",{"":"Todos",...B.kinds},filters.kind)}${select("category","Categoría",{"":"Todas",...B.categories},filters.category)}`:""}</div><div class="cash-actions"><button type="submit">APLICAR</button><button type="button" data-cash-action="book-period" data-period="all">TODO</button><button type="button" data-cash-action="book-period" data-period="month">ESTE MES</button><button type="button" data-cash-action="book-period" data-period="today">HOY</button>${full?'<button type="button" data-cash-action="book-csv">DESCARGAR EXCEL / CSV</button>':""}</div></form></details>`;
  }
  const addButton=pending=>`<button class="primary" data-cash-action="book-new" ${pending?"disabled":""}>REGISTRAR COMPRA O APORTE</button>`;
  function summary(snapshot,pending,filters,till){
    const rows=B.filter(B.journal(snapshot),{from:filters.from,to:filters.to}),s=B.summary(rows);
    const currencies=["UYU","BRL"].filter(c=>c==="UYU"||Object.values(s.currencies[c]).some(Boolean));
    const pendingWithdrawals=(snapshot.events||[]).filter(e=>e.kind==="withdrawal").map(e=>{const used=(snapshot.events||[]).filter(x=>x.related_id===e.id&&["settlement","return","writeoff"].includes(x.kind)).reduce((n,x)=>n+Number(x.amount_minor),0);return {...e,left:Number(e.amount_minor)-used};}).filter(e=>e.left>0);
    return `${toolbar(snapshot,filters,false)}<div class="cash-actions book-primary">${addButton(pending)}<button data-cash-action="tab" data-tab="caja">${till.active?"VER JORNADA ABIERTA":"ABRIR JORNADA"}</button><button data-cash-action="tab" data-tab="registro">VER TODOS LOS MOVIMIENTOS</button></div>
      ${till.active?`<div class="cash-panel"><div class="cash-header"><h2>Efectivo de la jornada</h2><span class="status ready">ABIERTA</span></div><p>${money(till.uyu)} · ${money(till.brl,"BRL")} esperados en caja.</p></div>`:'<p class="note">No hay jornada abierta. El resumen incluye también el historial anterior a la primera apertura.</p>'}
      <div class="book-stats">${stat("Ventas registradas",money(s.currencies.UYU.sales),`${s.salesCount} ventas del período`)}${currencies.map(c=>stat(`Compras y gastos · ${c}`,money(s.currencies[c].spending,c),"Incluye inversión inicial y mercadería")).join("")}${stat("Retiros pendientes",String(pendingWithdrawals.length),"En todas las jornadas")}</div>
      <div class="cash-panel"><h2>Ventas por medio de pago</h2>${Object.entries(s.payments).length?`<div class="cash-list">${Object.entries(s.payments).map(([method,n])=>`<div class="cash-list-row"><span>${esc(method)}${n.brl?`<small>Cobrado: ${money(n.brl,"BRL")}</small>`:""}</span><b>${money(n.uyu)}</b></div>`).join("")}</div><p class="note">Importes de venta en UYU. Los reales cobrados se muestran aparte, cuando se registraron.</p>`:'<p>No hay ventas registradas en este período.</p>'}</div>
      <div class="cash-panel"><h2>En qué se gastó</h2>${Object.entries(s.byCategory).length?`<div class="cash-list">${Object.entries(s.byCategory).sort((a,b)=>b[1]-a[1]).map(([key,n])=>{const [c,cat]=key.split(":");return `<div class="cash-list-row"><span>${esc(B.categories[cat]||cat)}</span><b>${money(n,c)}</b></div>`;}).join("")}</div>`:'<p>No hay compras ni gastos registrados en este período.</p>'}</div>
      <div class="cash-panel book-explanation"><h2>Datos por completar</h2><p>La ganancia todavía no se puede calcular con estos datos: hay inversión, compras de mercadería y gastos mezclados, y faltan los costos completos del período. Las ventas se toman automáticamente del historial de pedidos.</p>${s.unclassified?`<p><strong>${s.unclassified} compras o gastos por clasificar.</strong> Podés revisar los importados desde Registro → Corregir.</p>`:""}${s.unvalued?`<p><strong>${s.unvalued} aportes en bienes sin valorar.</strong> Se conservan con su descripción y no se suman como cero.</p>`:""}<p>El aporte de una persona y la compra que se paga con ese dinero se muestran por separado. Las transferencias entre personas no se suman como otro gasto.</p></div>`;
  }
  function people(snapshot,pending){
    const cash=B.journal(snapshot).filter(e=>e.source==="cash"&&["business_contribution","reimbursement"].includes(e.kind));
    const people=B.people([...(snapshot.book||[]),...cash]);
    return `<div class="cash-actions">${addButton(pending)}</div><div class="cash-panel"><h2>Lo que financió cada persona</h2><p>Dinero financiado acumulado. Los bienes se muestran aparte.</p><details><summary>Cómo se calcula</summary><p>Compras pagadas + dinero aportado + transferencias enviadas − transferencias recibidas − reintegros.</p><p>Este saldo no establece cuánto hay que devolver ni cómo se reparten las ganancias.</p></details></div>${people.length?people.map(p=>`<article class="cash-panel"><h2>${esc(p.name)}</h2>${["UYU","BRL"].filter(c=>Object.values(p[c]).some(Boolean)).map(c=>{const v=p[c];return `<div class="book-person-total"><span>Financiado neto · ${c}</span><strong>${money(v.net,c)}</strong></div><dl class="book-breakdown"><div><dt>Compras pagadas</dt><dd>${money(v.paid,c)}</dd></div><div><dt>Dinero aportado a Kebba</dt><dd>${money(v.contributed,c)}</dd></div><div><dt>Transferencias a otras personas</dt><dd>${money(v.sent,c)}</dd></div><div><dt>Recibido de otras personas</dt><dd>− ${money(v.received,c)}</dd></div><div><dt>Reintegros recibidos de Kebba</dt><dd>− ${money(v.reimbursed,c)}</dd></div>${v.inKind?`<div><dt>Bienes con valor registrado</dt><dd>${money(v.inKind,c)}</dd></div>`:""}${v.unvalued?`<div><dt>Aportes en bienes sin valorar</dt><dd>${v.unvalued}</dd></div>`:""}</dl>`;}).join("")}<button data-cash-action="book-person" data-person="${esc(p.name)}">VER MOVIMIENTOS</button></article>`).join(""):'<div class="empty">Todavía no hay aportes o pagos personales registrados.</div>'}`;
  }
  function register(snapshot,pending,filters){
    const rows=B.filter(B.journal(snapshot),filters);
    return `${toolbar(snapshot,filters,true)}<div class="cash-actions">${addButton(pending)}</div><p class="note">${rows.length} ${rows.length===1?"movimiento encontrado":"movimientos encontrados"}. Importe en la moneda indicada.</p>${rows.length?`<div class="book-register">${rows.map(e=>`<article class="cash-panel book-entry"><div class="cash-header"><div><small>${esc(labelDate(e.date))} · ${esc(B.kinds[e.kind]||e.kind)}</small><h2>${esc(e.description)}</h2></div><strong>${amountLabel(e)}</strong></div><p>${esc(e.person||"KEBBA")}${e.recipient?` → ${esc(e.recipient)}`:""}${e.supplier?` · ${esc(e.supplier)}`:""} · ${esc(B.categories[e.category]||(e.kind==="sale"?"Ventas":"Sin categoría"))}</p>${e.note?`<p class="book-note">${esc(e.note)}</p>`:""}<details><summary>Ver detalle e historial</summary><dl class="book-breakdown"><div><dt>Origen</dt><dd>${e.source==="sales"?"Pedido cobrado":e.source==="cash"?"Jornada de caja":e.source_key?"Excel importado":"Registro manual"}</dd></div>${e.source_key?`<div><dt>Referencia</dt><dd>${esc(e.source_key)}</dd></div>`:""}${e.document_number?`<div><dt>Comprobante</dt><dd>${esc(e.document_number)}</dd></div>`:""}${e.payment_method?`<div><dt>Medio de pago</dt><dd>${esc(e.payment_method)}</dd></div>`:""}<div><dt>Registrado</dt><dd>${esc(new Date(e.created_at).toLocaleString("es-UY"))}</dd></div></dl>${e.source==="book"?history(e,snapshot.book):""}${e.source==="book"?`<div class="cash-actions"><button data-cash-action="book-edit" data-id="${esc(e.id)}" ${pending?"disabled":""}>CORREGIR</button><button data-cash-action="book-void" data-id="${esc(e.id)}" ${pending?"disabled":""}>ANULAR CON MOTIVO</button></div>`:""}</details></article>`).join("")}</div>`:'<div class="empty">No hay movimientos que coincidan con estos filtros.</div>'}${audit(snapshot,filters)}`;
  }
  function history(entry,all){let e=entry,html="",steps=0;while(e.supersedes&&steps++<100){const old=all.find(x=>x.id===e.supersedes);if(!old)break;html+=`<p class="book-note">Corrección: ${esc(e.correction_reason)}. Anterior: ${esc(old.description)} · ${amountLabel(old)} · ${esc(old.person)}.${old.source_key?" Origen: "+esc(old.source_key):""}</p>`;e=old;}return html;}
  function audit(snapshot,filters){const voids=(snapshot.book||[]).filter(e=>e.kind==="void");const rows=B.filter(voids.map(e=>({...e,date:e.occurred_on})),filters);return rows.length?`<details class="cash-panel"><summary>Registros anulados (${rows.length})</summary>${rows.map(e=>`<p>${esc(labelDate(e.occurred_on))} · ${esc(e.description)} · ${esc(e.correction_reason)}</p>${history(e,snapshot.book)}`).join("")}</details>`:"";}
  const entryTypes={personal_payment:B.kinds.personal_payment,partner_transfer:B.kinds.partner_transfer,business_contribution:"Aporte a Kebba fuera de caja",reimbursement:"Reintegro fuera de caja",business_expense:B.kinds.business_expense,in_kind:B.kinds.in_kind};
  function form(entry={},values={}){
    const e={...entry,...values},kind=e.kind||"personal_payment",inKind=kind==="in_kind";
    const personLabel=kind==="reimbursement"?"Quién recibe el reintegro":kind==="partner_transfer"?"Quién entrega el dinero":kind==="personal_payment"?"Quién pagó la compra":kind==="business_expense"?"Quién registra el gasto":"Quién aporta";
    const methods={"":"Sin especificar",Transferencia:"Transferencia",PREX:"PREX",Pix:"Pix",Tarjeta:"Tarjeta","Otro fuera de caja":"Otro fuera de caja"};
    return `<p class="note">Para dinero que entra o sale del efectivo de hoy, usá Jornada → Ingreso o gasto. Aquí registrás inversión, pagos personales e históricos, y pagos fuera de esa caja.</p>${select("kind","Qué querés registrar",entryTypes,kind)}<div class="book-form-grid">${input("occurred_on","Fecha",e.occurred_on||B.localDay(new Date()),"date",`max="${B.localDay(new Date())}"`)}${input("person",personLabel,e.person||"","text",'maxlength="100" list="cash-person-list"')}${kind==="partner_transfer"?input("recipient","Quién recibe el dinero",e.recipient||"","text",'maxlength="100" list="cash-person-list"'):""}${select("currency","Moneda",{UYU:"Pesos uruguayos (UYU)",BRL:"Reales (BRL)"},e.currency||"UYU")}${input("amount",inKind?"Valor acordado (dejar vacío si no se sabe)":"Importe",e.amount??(e.amount_minor==null?"":(e.amount_minor/100).toFixed(2)),"text",'inputmode="decimal" placeholder="Ej.: 1250,50"',!inKind)}</div>${input("description",inKind?"Qué bienes se aportaron":"Concepto",e.description||"","text",'maxlength="240"')}${select("category","Categoría",B.categories,e.category||"unclassified")}${["business_expense","reimbursement"].includes(kind)?select("payment_method","Cómo pagó Kebba",methods,e.payment_method||""):""}<details ${e.supplier||e.document_number||e.note?"open":""}><summary>Proveedor, comprobante y notas</summary>${input("supplier","Proveedor (opcional)",e.supplier||"","text",'maxlength="150"',false)}${input("document_number","Número de comprobante (opcional)",e.document_number||"","text",'maxlength="100"',false)}<label class="cash-field">Notas<textarea name="note" rows="3" maxlength="1000">${esc(e.note||"")}</textarea></label></details>${entry.id?input("correction_reason","Motivo de la corrección",values.correction_reason||"","text",'minlength="5" maxlength="500"'):""}`;
  }
  window.KebbaBookUI={render:(section,snapshot,pending,filters,till)=>section==="resumen"?summary(snapshot,pending,filters,till):section==="personas"?people(snapshot,pending):register(snapshot,pending,filters),form,entryTypes,money};
})();
