const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../shifts.js'),'utf8');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const reads=html.slice(html.indexOf('const sharedLegacyReads='),html.indexOf('function applySharedState'));
const turn={id:'11111111-1111-4111-8111-111111111111',code:'T-20261008-001',opened_at:'2026-10-08T18:00:00Z',sales_count:2,total_uyu:420,payment_totals:[{method:'Pix',currency:'BRL',amountMinor:3855,amountUYU:320,paymentsCount:1,missingCount:0},{method:'Efectivo UYU',currency:'UYU',amountMinor:10000,amountUYU:100,paymentsCount:1,missingCount:0}]};
function boot(initial={active:turn,closed:[],enabled:true,connection:null,pendingOrders:0}){
 const events={},store=new Map(),calls=[],intervals=[];
 const ctx={window:{addEventListener(){}},document:{addEventListener(k,f){events[k]=f}},sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},sharedMode:true,sharedReady:true,sharedToken:'fixture',sharedVersion:2,sharedWriting:false,sharedPending:null,readBlocked:false,storageConflict:false,sharedReading:false,view:'shifts',modal:null,crypto:{randomUUID:()=> '22222222-2222-4222-8222-222222222222'},setInterval(){},setTimeout,Date,confirm:()=>true,render(){},safe:v=>String(v??'').replaceAll('<','&lt;'),money:v=>'$ '+v,toast(m){ctx.message=m},go(v){ctx.view=v},refreshShared:async()=>{},flushShared:async()=>{ctx.sharedPending=null},sharedRpc:async(name,body)=>{calls.push({name,body});return initial}};
 ctx.setInterval=fn=>intervals.push(fn);vm.createContext(ctx);vm.runInContext(reads,ctx);vm.runInContext(source,ctx);
 const run=code=>vm.runInContext(code,ctx),click=kind=>events.click({target:{closest:()=>({disabled:false,dataset:{shiftAction:kind}})}});
 return {ctx,run,click,calls,store,events,intervals,async tick(){await new Promise(r=>setImmediate(r));}};
}
test('turno muestra importes por moneda y conserva los reales registrados',async()=>{const a=boot();await a.tick();const html=a.ctx.window.KebbaShifts.render();assert.match(html,/R\$ 38,55/);assert.match(html,/100,00/);assert.match(html,/Falta conectar Google Sheets/);assert.equal(a.ctx.window.KebbaShifts.receiptTag().shiftId,turn.id);});
test('el cierre espera los últimos cobros y no declara enviado sin confirmación',async()=>{const a=boot();await a.tick();a.ctx.sharedPending={sale:1};let flushed=false;a.ctx.flushShared=async()=>{flushed=true;a.ctx.sharedPending=null;};a.ctx.sharedRpc=async(name,body)=>{if(name==='kebba_shift_action'){assert.equal(flushed,true);assert.equal(body.expected_version,2);return {active:null,closed:[{...turn,closed_at:'2026-10-08T19:00:00Z',exported_at:null}],enabled:true,connection:null,pendingOrders:0};}throw Error(name);};a.click('close');await a.tick();assert.match(a.ctx.window.KebbaShifts.render(),/Pendiente de envío/);assert.doesNotMatch(a.ctx.window.KebbaShifts.render(),/Enviado a Caja/);assert.equal(a.ctx.window.KebbaShifts.canCharge(),false);});
test('respuesta perdida reintenta el mismo cierre y evita nuevas operaciones',async()=>{const a=boot();await a.tick();const sent=[];a.ctx.sharedRpc=async(name,b)=>{if(name==='kebba_shift_action')sent.push(b);throw Error('Sin conexión');};a.click('close');await a.tick();a.click('open');await a.tick();assert.equal(sent.length,1);assert.equal(a.ctx.window.KebbaShifts.canCharge(),false);await a.tick();a.click('retry');await a.tick();assert.equal(sent.length,2);assert.equal(JSON.stringify(sent[0]),JSON.stringify(sent[1]));assert.match(a.ctx.window.KebbaShifts.render(),/REINTENTAR EL MISMO GUARDADO/);});
test('comprobar resuelve un cierre ya guardado aunque su respuesta se perdió',async()=>{const a=boot();await a.tick();a.ctx.sharedRpc=async()=>{throw Error('Sin conexión')};a.click('close');await a.tick();a.ctx.sharedRpc=async()=>({active:null,closed:[{...turn,closed_at:'2026-10-08T19:00:00Z',exported_at:'2026-10-08T19:01:00Z'}],enabled:true,connection:null,pendingOrders:0});await a.ctx.window.KebbaShifts.refresh();assert.equal(a.store.size,0);assert.match(a.ctx.window.KebbaShifts.render(),/Enviado a Caja/);});
test('pedidos sin cobrar y guardados fallidos impiden cerrar sin enviar solicitudes',async()=>{const a=boot({active:turn,closed:[],enabled:true,connection:null,pendingOrders:1});await a.tick();a.click('close');await a.tick();assert.equal(a.calls.length,1);assert.match(a.ctx.window.KebbaShifts.render(),/sin cobrar/);const b=boot();await b.tick();b.ctx.sharedPending={sale:1};b.ctx.readBlocked=true;b.click('close');await b.tick();assert.equal(b.calls.length,1);assert.match(b.ctx.window.KebbaShifts.render(),/sin guardar/);});
test('rechazo de versión conserva turno y permite comprobar antes de reintentar',async()=>{const a=boot();await a.tick();a.ctx.sharedRpc=async()=>{const e=Error('Los pedidos cambiaron');e.status=409;throw e};a.click('close');await a.tick();assert.equal(a.store.size,0);assert.equal(a.ctx.window.KebbaShifts.canCharge(),false);assert.match(a.ctx.window.KebbaShifts.render(),/Los pedidos cambiaron/);});
test('montos en reales faltantes se muestran pendientes y nunca como cero',async()=>{const a=boot({active:{...turn,payment_totals:[{method:'Pix',currency:'BRL',amountMinor:null,amountUYU:320,paymentsCount:1,missingCount:1}]},closed:[],enabled:true,connection:null,pendingOrders:0});await a.tick();assert.match(a.ctx.window.KebbaShifts.render(),/Importe pendiente/);assert.doesNotMatch(a.ctx.window.KebbaShifts.render(),/R\$ 0,00/);});
test('dos operadores que abren a la vez reciben el turno único sin guardado pendiente',async()=>{const a=boot({active:null,closed:[],enabled:true,connection:null,pendingOrders:0});await a.tick();a.ctx.sharedRpc=async()=>({active:turn,closed:[],enabled:true,connection:null,pendingOrders:0});a.click('open');await a.tick();assert.equal(a.store.size,0);assert.equal(a.ctx.window.KebbaShifts.receiptTag().shiftId,turn.id);assert.equal(a.ctx.window.KebbaShifts.canCharge(),true);});

test('lectura pequeña conserva el turno y detecta después la confirmación de Caja',async()=>{
 const a=boot({active:null,closed:[{...turn,closed_at:'2026-10-08T19:00:00Z',exported_at:null}],enabled:true,connection:null,pendingOrders:0,fingerprint:'first'});await a.tick();
 a.ctx.sharedRpc=async(name,body)=>{assert.equal(name,'kebba_shift_read_if_changed');assert.equal(body.known_fingerprint,'first');return {unchanged:true,fingerprint:'first'}};
 await a.ctx.window.KebbaShifts.refresh();assert.match(a.ctx.window.KebbaShifts.render(),/Pendiente de envío/);
 a.ctx.sharedRpc=async()=>({active:null,closed:[{...turn,closed_at:'2026-10-08T19:00:00Z',exported_at:'2026-10-08T19:01:00Z'}],enabled:true,connection:null,pendingOrders:0,fingerprint:'second'});
 await a.ctx.window.KebbaShifts.refresh();assert.match(a.ctx.window.KebbaShifts.render(),/Enviado a Caja/);
 a.ctx.document.visibilityState='hidden';const count=a.calls.length;a.intervals[0]();await a.tick();assert.equal(a.calls.length,count);
 let resumed=0;a.ctx.sharedRpc=async()=>{resumed++;return {unchanged:true,fingerprint:'second'}};a.ctx.document.visibilityState='visible';a.events.visibilitychange();await a.tick();assert.equal(resumed,1);
});
